GET http://localhost:8080/person/api
Accept: application/json

###

GET http://localhost:8080/person/api/all
Accept: application/json

###

GET http://localhost:8080/person/api/Hansi
Accept: application/json

###

GET http://localhost:8080/person/api/Hansi
Accept: application/xml

###

